#!/usr/bin/env python

from setuptools import setup

setup(name='asa_utils',
    version='0.1',
    description = "process data files generated by ANT's asa-lab EEG suite",
    author = 'Ian Dennis Miller',
    author_email = 'ian@saperea.com',
    url = 'http://code.google.com/p/asa-utils/',
    packages=['asa_utils'],
    long_description= """
    Process data files generated by Advanced Neuro Technology's asa-lab EEG suite. 
    This utility will combine results from multiple participants into a single 
    data file for statistical analysis.""",
    package_dir = {'': 'lib'},
    scripts=['bin/asa-utils.py'],
    # data_files = 't',
    license="GPL v2",
    platforms = ["any"],
)

